# Generated by Django 4.1.6 on 2023-02-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderproduct_variation_orderproduct_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order_number',
            new_name='order',
        ),
    ]
